version: '3'

services:
  wheelie_velodyne:
    build:
      context: .
      dockerfile: Dockerfile
    image: wheelie:velodyne
    container_name: wheelie_velodyne_container
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    shm_size: 8g
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
    devices:
      - /dev/snd
      - /dev/bus/usb

